#Adaptive Geolocated-data crawler: intelligent adaptive crawler for Google Place
#Monaco, D. (2019). An adaptive agent for Google Place crawling (No. 934). EasyChair
#3-clause BSD license
#Domenico Monaco, Tecnologie per persone, http://domenicomonaco.it

version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo:4.0.2
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    #- MONGO_INITDB_ROOT_USERNAME = usermongo
    #- MONGO_INITDB_ROOT_PASSWORD = passwordmongo
    ports:
      - "27020:27020"
    expose:
      - "27020"
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongodump:/data/dbdump
    command: mongod --port 27020 --smallfiles --logpath=/dev/null
    network_mode: bridge

